apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
  namespace: default
spec:
  secretName: wisecow-tls-selfsigned  
  issuerRef:
    name: selfsigned-cluster-issuer 
    kind: ClusterIssuer
  dnsNames:
    - wisecow.35.231.11.241.nip.io      
