apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow-app
          image: rashmi1408/wisecow:$GITHUB_SHA # Use the image you built earlier
          ports:
            - containerPort: 4499  # The port your app listens on inside the container
          imagePullPolicy: Always